# Generated by Django 5.0.6 on 2024-05-24 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputMultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('choices', models.TextField(help_text='Insira as opções separadas por vírgulas')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_multiple_choices', to='home.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_numbers', to='home.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_texts', to='home.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_times', to='home.form')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
