# Generated by Django 5.0.6 on 2024-07-03 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, choices=[(0, 'multiplaEscolha'), (1, 'alternativa'), (2, 'escala'), (3, 'descritiva')], null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.CharField(max_length=255)),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='home.historia')),
            ],
        ),
        migrations.CreateModel(
            name='Botao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=255)),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='botoes', to='home.pergunta')),
            ],
        ),
    ]
